version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    container_name: admin
    ports:
      - "3000:3000"

  customer:
    build:
      context: ./apps/customer
    container_name: customer-app
    ports:
      - "8081:8081"
    volumes:
      - ./apps/customer:/apps/customer

  driver:
    build:
      context: ./apps/driver
    container_name: driver-app
    ports:
      - "8082:8082"
    volumes:
      - ./apps/driver:/apps/driver

  owner:
    build:
      context: ./apps/owner
    container_name: owner-app
    ports:
      - "8083:8083"
    volumes:
      - ./apps/owner:/apps/owner

  db:
    image: postgres:16
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
